# Generated by Django 4.1.5 on 2023-02-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoitem_todolist_delete_todo_todoitem_todo_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='item_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
