# Generated by Django 4.1.5 on 2023-02-13 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todolist_item_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='item_name',
            new_name='list_name',
        ),
    ]
