# Generated by Django 4.1.5 on 2023-02-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_expense', '0002_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='item_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
