# Generated by Django 4.1.5 on 2023-01-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_bill_cleared_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='paid_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
