# Generated by Django 4.1.5 on 2023-01-24 18:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_bill_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='cleared_by',
        ),
        migrations.AddField(
            model_name='bill',
            name='cleared_by',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
