# Generated by Django 4.1.5 on 2023-01-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_bill_cleared_by_alter_bill_paid_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='paid_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='billtransaction',
            name='paid_amount',
            field=models.FloatField(default=0),
        ),
    ]
