# Generated by Django 4.1.5 on 2023-01-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_bill_amount_alter_bill_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payers',
            field=models.CharField(default='', max_length=200),
        ),
    ]
