# Generated by Django 4.1.5 on 2023-02-02 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_bill_payers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billtransaction',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(1, message="Can't be negative number")]),
        ),
    ]
