# Generated by Django 4.1.5 on 2023-02-02 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_billtransaction_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billtransaction',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(1, message='Pay at least 1 taka or higher! Not 0 or negative.')]),
        ),
    ]
