# Generated by Django 4.1.5 on 2023-02-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_billtransaction_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payers',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
