# Generated by Django 4.1.5 on 2023-02-02 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_bill_payers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 2, 19, 29, 3, 727534, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
